### ISSUE TITLE
About target

### ISSUE THREAD

**Issue by lucienne999** [BayesWatch/nas-without-training#11]
Hi, I notice that you are not using the loss to backward, rather the forward result. 

But leaving the target interface and the criterion in your code. I wonder why?  Are you trying to use the target to calculate the loss to backward but it looks bad?  

Related codes: 
https://github.com/BayesWatch/nas-without-training/blob/a98f8723c103423995c43ffe4f80fc4c37f06598/search.py#L58

https://github.com/BayesWatch/nas-without-training/blob/a98f8723c103423995c43ffe4f80fc4c37f06598/search.py#L50

**Comment by jack-willturner** [comment]
Good point!

This is just a piece of legacy code from one of our ablation tests.  In future we could remove it from the code but for now it's quite useful to have the targets there just so we can check any future developments against specific class labels.
