### ISSUE TITLE
derive cell structure from info

### ISSUE THREAD

**Issue by phtephanx** [BayesWatch/nas-without-training#12]
I would like to find commonalities between well performing architectures by parsing `info` of `InferCell`. I'm struggling to decipher the description of the cell structure, though.

example:
```python
info :: nodes=4, inC=64, outC=64, 
[1<-(I0-L0) | 2<-(I0-L1,I1-L2) | 3<-(I0-L3,I1-L4,I2-L5)],
|nor_conv_3x3~0|+|nor_conv_3x3~0|none~1|+|nor_conv_1x1~0|skip_connect~1|skip_connect~2|
```

Could you please break down how to interpret this? E.g. how to figure out which layers the skip connection links? Or point me to a documentation of `TinyNetwork`?

**Comment by phtephanx** [comment]
There are these 6 edges between 4 nodes which seem to be represented by 6 operations in the last line of the example. How do you count through the edges, though? I.e. which operation (== edge) connects which node?

**Comment by jack-willturner** [comment]
This cell syntax comes from NAS-Bench-201 so maybe this could be better answered as an issue on the NAS-Bench-201 repo! I'm afraid I've forgotten exactly how it works but I have written a very simple [visualisation script](https://github.com/BayesWatch/nas-without-training/blob/master/visualiser.py) which you can run to get pictures of the cells.

Example usage:

```bash
python visualiser.py --arch 6320
```

will show you a picture of the cell with ID 6320. 

Hope this helps!
