### ISSUE TITLE
ImageNet16-120 dataset download

### ISSUE THREAD

**Issue by nightstorm0909** [BayesWatch/nas-without-training#13]
Can anyone tell me how to download the ImageNet16-120 dataset? Or is it created from the original Imagenet dataset? If it is created from the original ImageNet dataset, can anyone tell me if there is a script that I can use to create the ImageNet16-120 dataset.

Thank you

**Comment by D-X-Y** [comment]
Hi @nightstorm0909 , ImageNet16-120 is a dataset created in [NATS-Bench](https://arxiv.org/pdf/2009.00437.pdf). You can see the description here: https://github.com/D-X-Y/NATS-Bench#preparation-and-download .
An example on how to create these datasets is at here: https://github.com/D-X-Y/AutoDL-Projects/blob/master/lib/datasets/get_dataset_with_transform.py#L167
