### ISSUE TITLE
Full imagenet performance 

### ISSUE THREAD

**Issue by sefibk** [BayesWatch/nas-without-training#14]
Thanks for the interesting work. 
Did you happen to experiment on the full Imagenet? Are results consistent for that dataset as well?

**Comment by jack-willturner** [comment]
Glad you enjoyed it!

The NAS-Bench-201 dataset doesn't have results for full-sized ImageNet, so we can't do the same kind of evaluation on it. 

If we wanted to use it on ImageNet we'd have to choose a cell search space, and then we would only be able to compare against whichever method proposed that specific cell space. An obvious thing to do might be to just compare against each different method+search space pair, but without training lots and lots of models we won't really know how effective either approach is. 

This is definitely something we want to look into in future but I think is a little far off at the moment so I'm going to close this issue for now.
