### ISSUE TITLE
About the score caculation

### ISSUE THREAD

**Issue by HandH1998** [BayesWatch/nas-without-training#20]
Hi! I have a question about the score caculation. In your code, you sum all the modules which has relu to caculate network.K, i.e. , the K_{H}. Then you caculate logdet(network.K) without normalization which should set the diagonal entry as 1. But in different network, the total number of modules which has relu is different. So without normalization the network.K，it seems to prefer the network which has more modules with relu. I would like to question if the normalization of the netwrk.K is necessary. In my opinion, the normaliztion may be right in some way? Hope you give me an answer. Thanks!

**Comment by jack-willturner** [comment]
Yes I imagine you could get some meaningful information out of the number of modules. 

However, there are plenty of datasets where the depth and width is fixed (thus the number of modules does not change), where our score works - which implies it is extracting more information than just the number of modules from the network.

Hope this helps!
