### ISSUE TITLE
cifar-split.txt

### ISSUE THREAD

**Issue by iksooman** [BayesWatch/nas-without-training#21]
I needed 'cifar-split.txt' to test 'sh scorehook.sh'.
In this project, I couldn't find the file.
After googling, I got 'cifar-split.txt' from PRDARTS project([https://github.com/salesforce/PR-DARTS/tree/main/PRDARTS_search/configs](url))

for someone who need help with this.

**Comment by jack-willturner** [comment]
sorry about this, now fixed (by b3a82a6642564df115f989ff940ec6b8ef9ca9d3)! thanks for pointing it out
