### ISSUE TITLE
It's possible to transform one of the best arch to tensorflow model?

### ISSUE THREAD

**Issue by brunogriep** [BayesWatch/nas-without-training#25]
I want to measure almost everything related to the "best" arch found. For example, model size in MB, how many bytes are used by the inferences, etc...
I only know how to do it with tensorflow API, so there's any way to import the final model, or any architecture and "transform" in a TF model?

**Comment by jack-willturner** [comment]
You should be able to go via [ONNX](https://github.com/onnx/onnx). 

Here's a tutorial on converting from PyTorch to ONNX:  https://pytorch.org/tutorials/advanced/super_resolution_with_onnxruntime.html

And a tutorial on converting from ONNX to Tensorflow: https://github.com/onnx/tutorials/blob/master/tutorials/OnnxTensorflowImport.ipynb

However, there are a couple of options for doing this kind of analysis in PyTorch, which I imagine will be much easier than going through a conversion process:
1. [torchprofile](https://github.com/zhijian-liu/torchprofile) 
2. the official [pytorch profiler](https://pytorch.org/blog/introducing-pytorch-profiler-the-new-and-improved-performance-tool/)
